# fly.toml app configuration file generated for oclabs-agent on 2026-04-07T16:00:55+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'oclabs-agent'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
